(() => {
  "use strict";
  const terms = window.INTERPRETER_TERMS.filter(term => term.publicationStatus === "Publicado" || term.publicationStatus === "Demo");
  const categories = ["Todos","Anatomía","Síntomas","Procedimientos","Medicamentos","Especialidades"];
  let query = "", category = "Todos", selected = terms[0], view = "dictionary", card = 0, revealed = false;
  let saved = JSON.parse(localStorage.getItem("is-saved-terms") || "[]");
  const $ = (selector) => document.querySelector(selector);
  const escape = (value) => String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const normalize = value => String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const filtered = () => terms.filter(t => (category === "Todos" || t.category === category) && (!query || normalize(`${t.en} ${t.es} ${t.definition} ${t.abbreviation || ""} ${t.synonymsEn || ""} ${t.synonymsEs || ""} ${t.spanishNeutral || ""} ${t.spanishUS || ""} ${t.spanishLatam || ""} ${t.regionalVariants || ""}`).includes(normalize(query))));

  function renderCategories(){ $("#categorias").innerHTML = categories.map(c => `<button class="${c===category?"selected":""}" data-category="${c}">${c}</button>`).join(""); }
  function renderList(){ const items = view === "saved" ? terms.filter(t => saved.includes(t.id)) : filtered(); $("#result-count").textContent=`${items.length} resultados`; $("#results-title").textContent=view==="saved"?"Mi lista":query?`Resultados para “${query}”`:"Términos esenciales"; $("#term-list").innerHTML=items.length?items.map(t=>`<button class="${selected.id===t.id?"current":""}" data-term="${t.id}"><span><strong>${escape(t.en)}</strong><small>${escape(t.es)}</small></span><em>${escape(t.category)}</em></button>`).join(""):`<div class="empty"><h3>No encontramos resultados</h3><p>Prueba otra palabra o selecciona “Todos”.</p></div>`; }
  function renderCard(){ const t=selected; $("#term-card").innerHTML=`<div class="term-top"><div><span class="category-label">${escape(t.category)}</span><h2>${escape(t.en)}</h2><h3>${escape(t.es)}</h3><p class="pronunciation">🔊 ${escape(t.pronunciation)}</p></div><button id="save-term" class="${saved.includes(t.id)?"saved":""}">${saved.includes(t.id)?"★ Guardado":"☆ Guardar"}</button></div><div class="term-section"><small>DEFINICIÓN</small><p>${escape(t.definition)}</p></div><div class="term-section context"><small>CONTEXTO CLÍNICO</small><p>“${escape(t.context)}”</p></div>${t.abbreviation?`<div class="term-section"><small>ABREVIATURA</small><p><strong>${escape(t.abbreviation)}</strong></p></div>`:""}${t.caution?`<div class="caution"><strong>Atención al contexto</strong><p>${escape(t.caution)}</p></div>`:""}<footer>✓ Ficha educativa · Requiere revisión profesional antes de publicación</footer>`; }
  function renderAll(){ renderCategories(); renderList(); renderCard(); $("#saved-count").textContent=saved.length; }
  function toggleSave(){ saved=saved.includes(selected.id)?saved.filter(id=>id!==selected.id):[...saved,selected.id]; localStorage.setItem("is-saved-terms",JSON.stringify(saved)); renderAll(); }
  function showView(next){ view=next; $("#practice-view").classList.toggle("d-none",next!=="practice"); $("#dictionary-view").classList.toggle("d-none",next==="practice"); document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===next)); if(next==="saved") $("#hero-title").textContent="Tus términos guardados."; else $("#hero-title").innerHTML="Encuentra el término correcto.<br>Interpreta con confianza."; if(next==="practice") renderPractice(); else renderAll(); }
  function renderPractice(){ const t=terms[card]; $("#flashcard").innerHTML=`<small>Tarjeta ${card+1} de ${terms.length}</small><span class="category-label">${escape(t.category)}</span><h2>${escape(t.en)}</h2>${revealed?`<h3>${escape(t.es)}</h3><p>${escape(t.definition)}</p>`:`<p class="reveal">Pulsa para revelar la respuesta</p>`}`; }
  document.addEventListener("click",e=>{ const target=e.target.closest("button,[data-term]"); if(!target)return; if(target.dataset.category){category=target.dataset.category;view="dictionary";renderAll();} if(target.dataset.term){selected=terms.find(t=>t.id===Number(target.dataset.term));renderAll();} if(target.id==="save-term")toggleSave(); if(target.dataset.view)showView(target.dataset.view); if(target.dataset.scroll)document.getElementById(target.dataset.scroll).scrollIntoView(); });
  $("#search-form").addEventListener("submit",e=>{e.preventDefault();query=$("#search-input").value.trim();const first=filtered()[0];if(first)selected=first;renderAll();});
  $("#flashcard").addEventListener("click",()=>{revealed=!revealed;renderPractice();}); $("#flashcard").addEventListener("keydown",e=>{if(e.key==="Enter"){revealed=!revealed;renderPractice();}});
  $("#previous-card").addEventListener("click",()=>{card=(card-1+terms.length)%terms.length;revealed=false;renderPractice();}); $("#next-card").addEventListener("click",()=>{card=(card+1)%terms.length;revealed=false;renderPractice();});
  renderAll();
})();
