window.INTERPRETER_TERMS = [
  {id:1,en:"Shortness of breath",es:"Dificultad para respirar",category:"Síntomas",pronunciation:"/short-nes ov breth/",definition:"Sensación de falta de aire o dificultad para respirar.",context:"The patient reports shortness of breath at rest.",caution:"No traducir literalmente como ‘cortedad de respiración’."},
  {id:2,en:"Blood pressure",es:"Presión arterial",category:"Signos vitales",pronunciation:"/blud preh-sher/",definition:"Fuerza que ejerce la sangre contra las paredes arteriales.",context:"We need to check your blood pressure.",abbreviation:"BP"},
  {id:3,en:"Complete blood count",es:"Hemograma completo",category:"Procedimientos",pronunciation:"/com-pleet blud count/",definition:"Análisis que mide células sanguíneas y otros componentes de la sangre.",context:"The provider ordered a complete blood count.",abbreviation:"CBC"},
  {id:4,en:"Over-the-counter medication",es:"Medicamento de venta libre",category:"Medicamentos",pronunciation:"/oh-ver the count-er med-i-kay-shun/",definition:"Medicamento que puede comprarse sin receta médica.",context:"Are you taking any over-the-counter medication?",abbreviation:"OTC"},
  {id:5,en:"Primary care physician",es:"Médico de atención primaria",category:"Especialidades",pronunciation:"/pry-mair-ee care fi-zish-an/",definition:"Profesional que brinda atención general y coordina referencias.",context:"Please follow up with your primary care physician.",abbreviation:"PCP"},
  {id:6,en:"Heartburn",es:"Acidez estomacal",category:"Síntomas",pronunciation:"/hart-burn/",definition:"Sensación de ardor en el pecho causada frecuentemente por reflujo.",context:"Spicy foods trigger my heartburn.",caution:"No significa ‘quemadura del corazón’."},
  {id:7,en:"Stool sample",es:"Muestra de heces",category:"Procedimientos",pronunciation:"/stool sam-pul/",definition:"Muestra utilizada para pruebas del sistema digestivo.",context:"Please collect a stool sample at home."},
  {id:8,en:"Dosage",es:"Dosis",category:"Medicamentos",pronunciation:"/doh-sij/",definition:"Cantidad y frecuencia indicadas para administrar un medicamento.",context:"Do not change the dosage without calling us."},
  {id:9,en:"Kidney",es:"Riñón",category:"Anatomía",pronunciation:"/kid-nee/",definition:"Órgano que filtra la sangre y produce orina.",context:"The scan shows a kidney stone."},
  {id:10,en:"Sprain",es:"Esguince",category:"Condiciones",pronunciation:"/sprayn/",definition:"Lesión de uno o más ligamentos alrededor de una articulación.",context:"The X-ray ruled out a fracture; it is a sprain."},
  {id:11,en:"Numbness",es:"Entumecimiento",category:"Síntomas",pronunciation:"/num-nes/",definition:"Pérdida total o parcial de la sensibilidad.",context:"Tell us if you feel numbness or tingling."},
  {id:12,en:"Discharge",es:"Secreción / alta médica",category:"Contexto",pronunciation:"/dis-charj/",definition:"Puede referirse a una secreción corporal o al alta de un centro médico.",context:"The meaning depends on the clinical context.",caution:"Verifica el contexto antes de interpretar."}
];
